services:
    postgres:
        image: 'postgres:latest'
        environment:
            - 'POSTGRES_DB=filmfit_core'
            - 'POSTGRES_PASSWORD=123'
            - 'POSTGRES_USER=postgres'
        ports:
            - '5434:5432'
